const seed=[{id:'local-1',type:'Emergency',icon:'✦',tone:'danger-bg',title:'Maya L. requested assistance',body:'Medical assistance requested near Cedar & 8th.',time:'2m',distance:'0.4 km',urgency:'critical',recommendation:'Alert nearby responders and maintain relay path.',signals:['life-safety language','emergency category']},{id:'local-2',type:'Hazard',icon:'!',tone:'hazard-bg',title:'Road blocked',body:'Fallen tree blocks the north entrance to Oak Street.',time:'8m',distance:'0.7 km',urgency:'high',recommendation:'Mark the route unsafe and request a second confirmation.',signals:['hazard language','access disruption']},{id:'local-3',type:'Resource',icon:'⌂',tone:'resource-bg',title:'Water point available',body:'Community water and charging point open until 20:00.',time:'12m',distance:'1.2 km',urgency:'normal',recommendation:'Share with the community and request verification.',signals:['community update category']}];
let updates=[...seed],connected=false;const $=s=>document.querySelector(s);const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function card(u){return `<article class="activity"><div class="activity-icon ${u.tone}">${u.icon}</div><div class="activity-copy"><b>${esc(u.title)}</b><p>${esc(u.body)}</p></div><time>${esc(u.time)}</time></article>`}function feedCard(u){return `<article class="feed-item"><div class="feed-top"><div class="activity-icon ${u.tone}">${u.icon}</div><div><span class="tag">${esc(u.type).toUpperCase()} · ${esc(u.urgency||'normal')}</span><b>${esc(u.title)}</b></div><span>${esc(u.time)} · ${esc(u.distance)}</span></div><p>${esc(u.body)}</p></article>`}
function renderAi(){const c=updates.filter(u=>u.urgency==='critical').length,h=updates.filter(u=>u.type==='Hazard').length,r=updates.filter(u=>u.type==='Resource').length;$('#criticalCount').textContent=c;$('#hazardCount').textContent=h;$('#resourceCount').textContent=r;const p=updates.find(u=>u.urgency==='critical')||updates.find(u=>u.urgency==='high')||updates[0];if(!p)return;$('#aiHeadline').textContent=c?'Critical incident needs attention':'No critical incident in the demo stream';$('#aiSummary').textContent=c?'AI ranked reports by life-safety language, hazard type, and disruption to access.':'AI is monitoring for life-safety and route-disruption signals.';$('#aiRecommendation').innerHTML=`<b>PRIORITY: ${esc(p.urgency||'normal').toUpperCase()}</b>${esc(p.recommendation||'Ask a responder to verify this update.')}`;$('#aiSignals').innerHTML=(p.signals||['community update category']).map(s=>`<span>${esc(s)}</span>`).join('')}
function render(){$('#activityList').innerHTML=updates.slice(0,3).map(card).join('');$('#nearbyList').innerHTML=updates.slice(0,3).map(card).join('');$('#feedList').innerHTML=updates.map(feedCard).join('');renderAi()}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
async function refresh(){try{const res=await fetch('/api/state',{cache:'no-store'});if(!res.ok)throw Error();const data=await res.json();updates=data.updates;connected=true;$('#peerCount').textContent=`${data.peers} nearby relays`;$('#syncStatus').textContent='Live demo hub synced just now';render()}catch{connected=false;$('#syncStatus').textContent='Offline demo mode — local updates only';render()}}
async function publish(payload){try{const res=await fetch('/api/updates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await res.json();if(!res.ok)throw Error(data.error);updates.unshift(data.update);connected=true;render();return true}catch(e){toast(e.message||'Could not reach demo hub');return false}}
function go(target){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${target}`));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.go===target));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.go;if(t==='report')return $('#reportDialog').showModal();go(t)}));$('#sosButton').addEventListener('click',()=>$('#sosDialog').showModal());
$('#confirmSos').addEventListener('click',async e=>{e.preventDefault();if(await publish({type:'Emergency',title:'A demo responder sent an SOS',body:$('#sosNeed').value,sender:'Phone demo responder',distance:'demo location'})){$('#sosDialog').close();toast('SOS relayed to every connected demo phone')}});
$('#submitReport').addEventListener('click',async e=>{e.preventDefault();const body=$('#reportDetails').value.trim();if(!body){toast('Add a short description before sharing');return}const raw=$('#reportType').value,type={'Available resource':'Resource','Community status':'Status'}[raw]||raw;if(await publish({type,body,sender:'Phone demo responder',distance:'demo location'})){$('#reportDialog').close();$('#reportDetails').value='';toast('Update relayed; AI triage is refreshed')}});
$('#connectionButton').addEventListener('click',()=>toast(connected?`${$('#peerCount').textContent}; live sync active`:'Demo hub unavailable; using local sample data'));document.querySelectorAll('.map-pin').forEach(p=>p.addEventListener('click',()=>toast(p.dataset.toast)));document.querySelectorAll('.filter').forEach(f=>f.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('selected'));f.classList.add('selected');const t=f.textContent;$('#feedList').innerHTML=(t==='All'?updates:updates.filter(u=>u.type.toLowerCase().includes(t.toLowerCase())||(t==='Urgent'&&u.urgency==='critical'))).map(feedCard).join('')||'<p class="hero-copy">No matching updates yet.</p>'}));$('#refreshAi').addEventListener('click',()=>{renderAi();toast('AI brief refreshed from the live incident stream')});
$('#clearData').addEventListener('click',async()=>{try{await fetch('/api/reset',{method:'POST'});await refresh();toast('Shared demo data restored')}catch{updates=[...seed];render();toast('Local demo data restored')}});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();refresh();setInterval(refresh,2500);
